version: 2
jobs:
  test-api:
    docker:
      - image: node

    working_directory: ~/project/api

    steps:
      - checkout
      - run: |
          yarn install
          yarn lint
          yarn test
  test-admin-ui:
    docker:
      - image: node

    working_directory: ~/project/admin-ui

    steps:
      - checkout
      - run: |
          yarn install
          yarn lint
          yarn test
workflows:
  version: 2
  test_all:
    jobs:
      - test-api
      - test-admin-ui
