version: 2
jobs:
  test-api:
    docker:
      - image: node:8-slim
    steps:
      - checkout
      - run: |
          cd api
          yarn install
          yarn lint
          yarn test
  test-admin-ui:
    docker:
      - image: node:8-slim
    steps:
      - checkout
      - run: |
          cd admin-ui
          yarn install
          yarn lint
          yarn test
workflows:
  version: 2
  test_all:
    jobs:
      - test-api
      - test-admin-ui
