version: 2
jobs:
  test-api:
    docker:
      - image: node

    working_directory: ~/repo/api

    steps:
      - checkout
      - run: yarn install
      - run: yarn lint
      - run: yarn test
  test-admin-ui:
    docker:
      - image: node

    working_directory: ~/repo/admin-ui

    steps:
      - checkout
      - run: yarn install
      - run: yarn lint
      - run: yarn test
