env:
  node: true
  es6: true
  commonjs: true
  mocha: true
extends: 'airbnb-base'
plugins:
  - mocha
parserOptions:
  ecmaVersion: 2018
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  func-names: off
  import/prefer-default-export: off
